language: python
python: 3.5

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  pip: true
  directories:
    - "$HOME/virtualenv/python3.5.1/lib/python2.7/site-packages/"
    - "$HOME/virtualenv/python3.5.1/bin/"

install:
  - pip install -r requirements.txt

script:
  - python build.py build

after_success:
  - coveralls
